#include "bsp_system.h"
#include "FFT.h"
#include "mqtt.h"
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER


system_parameter sp = {//----系统变量
	.system_mode=0,
	.up_num=0,
	.down_num=0,
	.interrupt_num=0,
	.energy_comsumption=0,
	.relay_mode=3,
	.auto_flag=0,
	.processing_flag=0,
	.cut_flag=0,
	.pow_max=1000,
	.classify_flag=0
};


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
	systick_init(1000);//初始化systick时钟
	gpt0_init();//初始化定时器
	fft_init();//FFT初始化
	scheduler_init();//初始化调度器
	ADC_Init();//初始化ADC
	volt_rms_calcu();
	elect_rms_calcu();
	R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_SECONDS);//等待初始化 延时1秒
	uart_init();//初始化串口
	Mqtt_Init();//qt初始化
	printf("page 0\xff\xff\xff");
	R_IOPORT_PinWrite(&g_ioport_ctrl,BSP_IO_PORT_07_PIN_12,1);
	while(1){//---------------主函数
		//-----调度器运行
		scheduler_run();
		
	}

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart (bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
